### ISSUE TITLE
Краш с модом Galacticraft

### ISSUE THREAD

**Issue by fogss** [Bogdan-G/FFoKC#1]
Добрый день, если запускать с модом Galacticraft 1710 latest сразу краш.

Time: 19.05.17 10:57
Description: Exception in server tick loop

java.lang.VerifyError: Expecting a stack map frame
Exception Details:
  Location:
    net/minecraft/world/World.func_72867_j(F)F @6: getfield
  Reason:
    Error exists in the bytecode
  Bytecode:
    0x0000000: 2a23 b80b 0cae b408 aeb4 087e b408 ae23
    0x0000010: 62                                     

	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:367)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

**Comment by Bogdan-G** [comment]
добавить в параметр запуска аргумент: -noverify

**Comment by fogss** [comment]
Добрый день, спасибо ) а что дает данный параметр?

**Comment by Bogdan-G** [comment]
выключает верификацию(один из видов) кода если кратко.

**Comment by Bogdan-G** [comment]
проблема решена? тогда закрою исус.

**Comment by fogss** [comment]
Добрый день, да все решено ,спасибо))

**Comment by Bogdan-G** [comment]
незачто, обращайтесь еще =)

**Comment by fogss** [comment]
Конечно будем))ваш форк самый живой и рабочий))причем работает намного лучше чем остальные

**Comment by Bogdan-G** [comment]
это не сарказм?)) я так же еще имел ввиду, что я никуда не "пропал".

**Comment by fogss** [comment]
Не сарказм, я серьезно)
