### ISSUE TITLE
Добавление команды /thermos tps

### ISSUE THREAD

**Issue by fogss** [Bogdan-G/FFoKC#2]
Добрый день, в последних билдах термоса есть очень удобная команда /thermos tps она показывает отставания по мирам в ms, можно ли ее добавить в ваш билд? был бы очень признателен)

**Comment by Bogdan-G** [comment]
разве эта команда не клон `/forge tps` и/или `/cofh tps` и/или `/tps`? 
Еще в оригинальном котле была `/cauldron chunks` , тоже возможно в тему, но да все они не разукрашены)

**Comment by fogss** [comment]
Спасибо попробую))

**Comment by Bogdan-G** [comment]
что то изменилось? исус закрывать или предложение все еще в силе?

**Comment by maximcs1** [comment]
Закрывай, forge tps = thermos tps
