### ISSUE TITLE
MaxCoordinatesInOverworld Работает странно.

### ISSUE THREAD

**Issue by maximcs1** [Bogdan-G/FFoKC#3]
За пределами данных координат, сервер генерирует чанки без деревьев и любой растительности. Только голые чанки с травой. При ломании блока происходит рассинхрон и клиент не может попасть внутрь.
Билд: Самый новый

**Comment by Bogdan-G** [comment]
за пределами 1млн+ уже глючит ген, это из ванили идет. В ней же _были_ чеки на 3млн координаты, часть кода просто игнорила этот фактор и были дополнительно добавлены проверки, и параметр вынесен из кода в конфиг.

**Comment by maximcs1** [comment]
Лучше бы не генерировать чанки вовсе за пределами этих координат)
И работает ли ограничение для других миров?

**Comment by Bogdan-G** [comment]
у др миров зависит от их реализации, в коде были константы  - или + 3млн, и это вынесено в конфиг, это файлы(не точно) World, CommandBase, ChunkCache, параметр внутри называется `MAX_BLOCK_COORD`, это про блоки по сути. https://github.com/Bogdan-G/FFoKC/commit/89713e32e25510e24286fc57f3f50a8e757c5ade , мб еще коммит был про это.
